# Generated by Django 4.2.6 on 2023-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
